#!/usr/bin/env bash
PS1='$ '
source ~/.bashrc
conda activate alfarvis
if [ $? -ne 0 ]; then
  echo "Failed to activate conda environment"
  exit
fi
CUR_DIR=`dirname "$0"`

python $CUR_DIR/qt_notebook.py
